// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeX00Myg65WK8uQpNneEDwfd32udYVv8Y',
    appId: '1:698313883616:web:9a49d344d944ebf3953585',
    messagingSenderId: '698313883616',
    projectId: 'invernadero-multi',
    authDomain: 'invernadero-multi.firebaseapp.com',
    databaseURL: 'https://invernadero-multi-default-rtdb.firebaseio.com',
    storageBucket: 'invernadero-multi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGzkC2a85LfzVQCmS1c4HHBQVizqXhYAw',
    appId: '1:698313883616:android:d491c3b950d2eb96953585',
    messagingSenderId: '698313883616',
    projectId: 'invernadero-multi',
    databaseURL: 'https://invernadero-multi-default-rtdb.firebaseio.com',
    storageBucket: 'invernadero-multi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFVI4LU7aUIsSboir1pOfL3_jmEZnSw3o',
    appId: '1:698313883616:ios:9c4675dbca54962b953585',
    messagingSenderId: '698313883616',
    projectId: 'invernadero-multi',
    databaseURL: 'https://invernadero-multi-default-rtdb.firebaseio.com',
    storageBucket: 'invernadero-multi.firebasestorage.app',
    iosBundleId: 'com.dijk.invernadero.invernaderoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFVI4LU7aUIsSboir1pOfL3_jmEZnSw3o',
    appId: '1:698313883616:ios:9c4675dbca54962b953585',
    messagingSenderId: '698313883616',
    projectId: 'invernadero-multi',
    databaseURL: 'https://invernadero-multi-default-rtdb.firebaseio.com',
    storageBucket: 'invernadero-multi.firebasestorage.app',
    iosBundleId: 'com.dijk.invernadero.invernaderoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeX00Myg65WK8uQpNneEDwfd32udYVv8Y',
    appId: '1:698313883616:web:e50de15b91bf73a0953585',
    messagingSenderId: '698313883616',
    projectId: 'invernadero-multi',
    authDomain: 'invernadero-multi.firebaseapp.com',
    databaseURL: 'https://invernadero-multi-default-rtdb.firebaseio.com',
    storageBucket: 'invernadero-multi.firebasestorage.app',
  );
}
